### ISSUE TITLE
Setup time of pixhawk not read by CC

### ISSUE THREAD

**Issue by hflemmen** [tum-phoenix/phx-flight-ros-golden-snitch#3]
# Details
For now, the setup of the EKF in Ardupilot is taking quite a while. In this timespan we can't arm the vehicle. We should be able to detect the state via mavlink, but that is not yet done. Therefore we account for this delay by sleeping the CC for a little too long, causing unnecessary delay.

#Tasks

- [x]  Ask on discuss.ardupilot.org of which message to read from.
- [ ] Test the resulting working fix.

# Criteria

* We wait no longer than needed to declare the drone flight ready.

**Comment by hflemmen** [comment]
https://discuss.ardupilot.org/t/monitor-ekf-status-await-ekf-initialized/54521

**Comment by hflemmen** [comment]
Currently waiting for answer about how to do this waiting with Mavros. Might just abuse "arm" by trying to arm to check if it is ready to arm

**Comment by FabianBell** [comment]
# Done 
Close it because we do not get response.
