### ISSUE TITLE
Increase Robustness of human-avoidance 

### ISSUE THREAD

**Issue by KonstantinIkonomou** [tum-phoenix/phx-flight-ros-golden-snitch#4]
# Details 
* human_info/src/run.py has class Processor
* makes decision on where to go based on input from camera 

* human is not always detected, in order to make the avoidance more efficient the robustness of the human avoidance needs to improve

# Tasks
- [x] enable some sort of memory
- [x] create a filter over samples (suited weights, suited filter)
- [x] unit testing

# Criteria
* filters out misdetections 
* as long as it still returns reasonable output

**Comment by hflemmen** [comment]
I did not think of it yesterday, but some of the detection were way off. Like they detected something in the background or foreground. I guess that these will deteriorate the accuracy quite a lot, but they might be quite easy to avoid with some outlier detection. We can for example discard(not filter, but just ignore) all detection that are "far" from the previous position or "far" from where it would have been if it had moved linearly.

**Comment by FabianBell** [comment]
> I did not think of it yesterday, but some of the detection were way off. Like they detected something in the background or foreground. I guess that these will deteriorate the accuracy quite a lot, but they might be quite easy to avoid with some outlier detection. We can for example discard(not filter, but just ignore) all detection that are "far" from the previous position or "far" from where it would have been if it had moved linearly.

The model keypoints have a parameter 'score', which expresses the confidence of the prediction. The script already discards some of the prediction based on a threshold. We might adjust the threshold further.

**Comment by hflemmen** [comment]
That sounds like a reasonable threshold to tune, but I still think that it makes sense to discard (at least extreme) outliers based on how far away they are from their previous position.

**Comment by KonstantinIkonomou** [comment]
Issues so far:

* How many samples are feasible? 
To have good perfomance the samplesize should be as small as possible. However, a filter works best with more samples. Fine-Tuning and Testing required

*  memory can be implemented as a list 

* Kalman filter requires much effort to implement and to compute

**Comment by KonstantinIkonomou** [comment]
### Solved: 
- class filter.py contains basic average filter
- Can be modified in future (e.g. median for larger sample sizes)
- considers **all** output from HumanPos() , does not refer to keypoints 

### Issues:
- if feasible, filtering should happen earlier in the process (e.g. in keypoint confidence)
- performance not tested yet, same goes for beginner mistakes 
- sample size not tested

**Comment by KonstantinIkonomou** [comment]
max_distance should be in pixels, not 0.5

**Comment by hflemmen** [comment]
I have now implemented this as it's own filter working at the pixel locations of the keypoints. All tests passed on my pc, but I have not tested it on the pi.
