### ISSUE TITLE
Rosbag Camera node

### ISSUE THREAD

**Issue by FabianBell** [tum-phoenix/phx-flight-ros-golden-snitch#8]
# Details
We need to simulate the camera if we want to to test the system headless. For that we need to catch the camera node output with [rosbag](http://wiki.ros.org/rosbag).

# Tasks

- [x] Write script to catch output
- [x] Test script

**Comment by FabianBell** [comment]
60 sec rosbag tages ca. 1.2 GB. I hope that it is okay if I leave that on the pi.

**Comment by hflemmen** [comment]
I guess that is acceptable. I don't remember, but I think we used a 64GB SD-card(At least a 32GB one). Note that if you want longer ones, you can use the [https://wiki.ros.org/compressed_image_transport](compressed image message) to save space. You just have to also uncompress it when you play the bag.

**Comment by FabianBell** [comment]
# Done
I have created a rosbag with Dominik. Is is 37 secs long. It somehow missed one or two seconds but I think for testing it is okay. I converted it into a 30 sec mp4. Everything is in ~/rosbags on the pi.
