### ISSUE TITLE
Observation Node

### ISSUE THREAD

**Issue by FabianBell** [tum-phoenix/phx-flight-ros-golden-snitch#9]
# Details
We need a node for observing the camera input and human info. 

* Make a publicher for images called something like `debug_img`
* If someone subscribes to that topic, do all the resizing, drawing etc. that is needed for the debug image and publish.
* Then we can see the debug stream with `rqt_viewer` and we don't have to change the code to switch between debuging/not debuging.

# Tasks

* [ ] implement logic for generating debug images
* [ ] implement node

# Criteria

* Write node that displays camera input and essential human info
* Test node

**Comment by FabianBell** [comment]
I get the following error when using `rqt_image_view /observe`:
```
libEGL warning: DRI3: failed to query the version
libEGL warning: DRI2: failed to authenticate
Could not import "pyqt" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/home/pi/ros_catkin_ws/src/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    from . import libqt_gui_cpp_sip
ImportError: /home/pi/ros_catkin_ws/devel/lib/python3/dist-packages/qt_gui_cpp/libqt_gui_cpp_sip.so: undefined symbol: PyModule_Create2

qt_gui_main() found no plugin matching "rqt_image_view/ImageView"
try passing the option "--force-discover"
```

I cannot find a solution. @hflemmen any idea?

**Comment by hflemmen** [comment]
I guess `rqt_image_view` is not made for remote displays. I am not sure how to fix this, but `rviz` works. The issue with `rviz` is that it is very slow and I guess `rqt_image_view` should be faster.

**Comment by hflemmen** [comment]
Seems like this might be a common issue with `qt` on pis: https://pi3d.github.io/html/FAQ.html#glx-dri2-not-supported-or-failed-to-authenticate

**Comment by hflemmen** [comment]
This one was more up to date: https://catonrug.blogspot.com/2018/01/libegl-warning-dri2-failed-authenticate.html.

I'll try it now.

**Comment by hflemmen** [comment]
Ok, the first issue disapeared, but this remains:

Could not import "pyqt" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/home/pi/ros_catkin_ws/src/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    from . import libqt_gui_cpp_sip
ImportError: /home/pi/ros_catkin_ws/devel/lib/python3/dist-packages/qt_gui_cpp/libqt_gui_cpp_sip.so: undefined symbol: PyModule_Create2

qt_gui_main() found no plugin matching "rqt_image_view/ImageView"
try passing the option "--force-discover"

It might be a python2/3 issue: https://answers.ros.org/question/255218/rosrun-rqt_graph-rqt_graph-shows-error/

**Comment by hflemmen** [comment]
The quickfix in the previous link did not solve the issue(and we want to still use python3 for other things). I could not figure it out, but I guess it is a problem with `qt` on the pi.

**Comment by FabianBell** [comment]
Do you think [image_view](http://wiki.ros.org/image_view) instead of [rqt_image_view](http://wiki.ros.org/rqt_image_view) would work?

**Comment by hflemmen** [comment]
Might be. If it don't use `qt` perhaps it is better.

**Comment by hflemmen** [comment]
I think I had some issues building it, so I left it out. I can do a new attempt on building it.

**Comment by hflemmen** [comment]
I installed gtk2.0, and now it builds, but when I run it I get 
`(image:7381): Gtk-ERROR **: 11:07:53.142: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
`

**Comment by FabianBell** [comment]
I would say that we just write a small script in order to view image topics if those scripts not work. It is not a big issue.

**Comment by hflemmen** [comment]
I did not find a solution, but it seems like it requires gtk2, while one of the dependencies need gtk3. Might we we can just change every use of gtk2 to gtk3 in the code and make it run. Perhaps we also should open an issue in the image_pipeline repository.

**Comment by FabianBell** [comment]
I have added a small script for that and installed it on the pi. You can use it as `view_topic <topic>`. An example would be `view_topic /camera/image_raw`.

**Comment by hflemmen** [comment]
Nice! Should we make it a ros-package, so we can run the script with rosrun?

Also, what is the `observer` package?

**Comment by FabianBell** [comment]
> Nice! Should we make it a ros-package, so we can run the script with rosrun?

No, I since it is not a proper node I would leave it as a script.  

> Also, what is the `observer` package?

That is the ros-package I am working on for debugging the drone.

**Comment by FabianBell** [comment]
Depends on Issue #8 in order to do a proper testing. I will continue this issue after that.

**Comment by FabianBell** [comment]
# Done
I finished the implementation. It shows the distance. I think this is enough for now. We can extenbd it later.
